# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4468e9c3d32b330a85174a632f0af798141fa4010ef3e747596cc099d9dae8b92cce59f2d7adf89741c4bcc195d95f865480c322ca9240265e1b27f2dff4817a

test:
  secret_key_base: 90b16c108c50382d493698737e64c82de15c233b85975859bee294b93f8e1c93c8c97d3130f05f4acaf0ab8f952dc6a2774c0a4cbec70930b8c12bfc97482562

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
